titlesize=25
labelscale = 0.025
labelmargin=0.20 #Labeling
canvaswidth = 750
canvasheight= 800
defaultlabelsize = canvasheight*labelscale 
titlesize=defaultlabelsize*1.4
atlasStatus="Internal"
sqrts  = 13 
